<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\ProcurementCopilot.Console\ProcurementCopilot.Console.csproj" />
    <ProjectReference Include="..\..\src\ProcurementCopilot.Testing\ProcurementCopilot.Testing.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
  </ItemGroup>
</Project>
